### ISSUE TITLE
The download link for Glioma dataset

### ISSUE THREAD

**Issue by wwxb2012** [Kaminyou/URUST#18]
The original dataset download link for Glioma dataset https://www.data.mendeley.com/datasets/vkt6p2xztv/2 seems to be failed. Could you kindly share the dataset?

**Comment by Kaminyou** [comment]
Our Glioma dataset is a private one but not this public one. Please use other [public datesets](https://github.com/Kaminyou/URUST?tab=readme-ov-file#quick-instruction) described in README.
